// ================================
// ENUMS — Dominio congelado v2.0.0
// ================================

export enum TicketStatus {
  OPEN = 'OPEN',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum ImpactLevel {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFO = 'INFO',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  TECNICO = 'TECNICO',
  INGENIERO = 'INGENIERO',
}

export enum TicketEventType {
  CREATED = 'CREATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
  UPDATED = 'UPDATED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  IMPORTED_FROM_LIBRENMS = 'IMPORTED_FROM_LIBRENMS',
}

export enum TicketSource {
  MANUAL = 'MANUAL',
  LIBRENMS = 'LIBRENMS',
  IMPORTED = 'IMPORTED',
}

export enum ServiceContractName {
  // Internet dedicado
  INTERNET_DEDICADO_100_MB = 'INTERNET_DEDICADO_100_MB',
  INTERNET_DEDICADO_200_MB = 'INTERNET_DEDICADO_200_MB',
  INTERNET_DEDICADO_500_MB = 'INTERNET_DEDICADO_500_MB',
  INTERNET_DEDICADO_1_GB = 'INTERNET_DEDICADO_1_GB',
  INTERNET_DEDICADO_2_GB = 'INTERNET_DEDICADO_2_GB',
  INTERNET_DEDICADO_4_GB = 'INTERNET_DEDICADO_4_GB',
  INTERNET_DEDICADO_10_GB = 'INTERNET_DEDICADO_10_GB',

  // Internet compartido
  INTERNET_COMPARTIDO_100_MB = 'INTERNET_COMPARTIDO_100_MB',
  INTERNET_COMPARTIDO_200_MB = 'INTERNET_COMPARTIDO_200_MB',
  INTERNET_COMPARTIDO_500_MB = 'INTERNET_COMPARTIDO_500_MB',
  INTERNET_COMPARTIDO_1_GB = 'INTERNET_COMPARTIDO_1_GB',
  INTERNET_COMPARTIDO_2_GB = 'INTERNET_COMPARTIDO_2_GB',
  INTERNET_COMPARTIDO_4_GB = 'INTERNET_COMPARTIDO_4_GB',
  INTERNET_COMPARTIDO_10_GB = 'INTERNET_COMPARTIDO_10_GB',

  // Enlaces
  ENLACE_PUNTO_A_PUNTO = 'ENLACE_PUNTO_A_PUNTO',
}
